# Generated by Django 5.0.2 on 2024-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('stock_status', models.BooleanField()),
                ('available_stock', models.IntegerField()),
            ],
        ),
    ]
